name: sdss2022
channels:
  - conda-forge
dependencies:
  - python=3.10
  - bokeh
  - clustergram
  - geopy
  - ipywidgets
  - matplotlib=3.5.3
  - momepy
  - osmnx
  - pandas=1.4.4
  - pygeos
  - scikit-learn
  - splot
  - watermark
